application: roomscheduler490
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /rooms\.html
  script: main.py
  
- url: /help\.html
  script: main.py
  
- url: /equipment\.html
  script: main.py
  
- url: /roomsuccess\.html
  script: main.py
  
- url: /roomfailure\.html
  script: main.py

- url: /roomlist\.html
  script: main.py

- url: /.*
  script: main.py