application: roomscheduler490
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: jinja2
  version: "2.6"
  
  
handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /static
  static_dir: static
  
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /rooms\.html
  script: main.py
  
- url: /help\.html
  script: main.py
  
- url: /equipment\.html
  script: main.py
  
- url: /equipsuccess\.html
  script: main.py
  
- url: /equipfailure\.html
  script: main.py
  
- url: /roomsuccess\.html
  script: main.py
  
- url: /roomfailure\.html
  script: main.py

- url: /roomlist\.html
  script: main.py

- url: /.*
  script: main.py